name: NinjaWorksPlugin
version: '${project.version}'
main: NinjaWorksPlugin
api-version: 1.19
authors: [ frisby_ninja ]
description: The official plugin for the Ninja_Works server.
website: https://www.youtube.com/channel/UCklNX1VXDpoU-cHOUXO-LTw
commands:
  arrowremover:
    description: Removes arrows from the given player.
    usage: /removearrows [player]